- name: create a new EC2 key pair, returns generated private key
  # use no_log to avoid private key being displayed into output
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    state: absent
#  no_log: true
  register: key_pair
- debug:
    msg: "{{ key_pair }}"
